### ISSUE TITLE
Type error in DiffToolkit

### ISSUE THREAD

**Issue by dktcoding** [yetanotherape/diff-match-patch#11]
There's bug in:

https://github.com/yetanotherape/diff-match-patch/blob/ddbf7c0c021b970533a161f8078f675dcd7e5372/src/DiffToolkit.php#L193

This should be:

```php
 if (mb_strlen($hm1[4]) > mb_strlen($hm2[4])) { 
```

**Comment by yetanotherape** [comment]
@dktcoding thank you for spotting the bug!
