### ISSUE TITLE
Multibyte characters lead to incorrect diffs on specific server

### ISSUE THREAD

**Issue by floscher** [yetanotherape/diff-match-patch#3]
I currently run into problems when trying to diff strings which contain multibyte characters.

I created an minimal example which shows  the problem:
```php
<!DOCTYPE html>
<meta charset=utf8>
<?php
require_once 'src/DiffMatchPatch/DiffMatchPatch.php';
require_once 'src/DiffMatchPatch/DiffToolkit.php';
require_once 'src/DiffMatchPatch/Diff.php';
require_once 'src/DiffMatchPatch/Match.php';
require_once 'src/DiffMatchPatch/Patch.php';
require_once 'src/DiffMatchPatch/PatchObject.php';
require_once 'src/DiffMatchPatch/Utils.php';

use DiffMatchPatch\Diff;

$string1 = 'abc „def“ ghi';
$string2 = 'abc  bla „def“ ghi';

$diff = new Diff($string1, $string2);

echo sprintf(
	'<h2>Text 1</h2><pre>%s</pre><h2>Text 2</h2><pre>%s</pre><h2>Delta</h2><pre>%s</pre>',
	$diff->text1(),
	$diff->text2(),
	$diff->toDelta()
);
?>
```

On my local machine this produces the intended result:
![local-result](https://cloud.githubusercontent.com/assets/3904348/8638071/a8eb8104-28ae-11e5-980f-50667d8789b9.png)

But when I upload it to a production-server I work with, the result looks like this:
![production-result](https://cloud.githubusercontent.com/assets/3904348/8638076/bdbca8c4-28ae-11e5-9195-339fc69d0796.png)

The production server runs PHP Version 5.3.3-7+squeeze25, here is an excerpt of probably the most important parts of phpinfo() for this issue:
![phpinfo](https://cloud.githubusercontent.com/assets/3904348/8638108/a0f39ddc-28af-11e5-9f07-8e35149ca054.png)

Do you have any idea where this problem comes from and especially what I could do to solve this?

**Comment by yetanotherape** [comment]
Hi! Can you give me the result of your local `phpinfo()`?

**Comment by floscher** [comment]
Sure, I sent it to you via Mail.

I narrowed the problem down to `mb_substr()` and `mb_strlen()` giving contradicting results on the production server (`$string != mb_substr($string, 0, mb_strlen($string))`):
* I put the string `„abc“` into a variable `$string` (those quotes are part of the string)
* Then I convert it to `UCS-2LE` with `iconv(mb_internal_encoding(), 'UCS-2LE', $string)`
* Now I set `mb_internal_encoding('UCS-2LE')`
* `mb_strlen($string)` gives me 9 then
* `mb_substr($string, 0, 9)` gives me only `���ab` instead of the complete string

This causes problems e.g. in the method [DiffToolkit->commonPrefix()](https://github.com/yetanotherape/diff-match-patch/blob/187a1c412f59b303a23f6de8a2f95f60c4965735/src/DiffMatchPatch/DiffToolkit.php#L40).

**Comment by yetanotherape** [comment]
It seems your production server doesn't like UCS-2LE. Try to replace all its mentions  to UTF-8.

**Comment by floscher** [comment]
Thank you for your help. This solution seems to work, although some PHPUnit tests fail when I change all occurences of UCS-2LE to UTF-8.
