### ISSUE TITLE
Is this done and usable?

### ISSUE THREAD

**Issue by nisargjhaveri** [yetanotherape/diff-match-patch#4]
I'm asking this as the README still says,

> **NOTE: This is alpha software and is under development.**

But, at the same time, the README is not updated in last 2 years whereas I can see a lot of other commits.

What is the state of the project? If not in a good condition, any alternative for `google-diff-match-patch` in php?

**Comment by yetanotherape** [comment]
I forgot to update README file. The project is stable.

**Comment by nisargjhaveri** [comment]
Thanks a lot. :)
